services:
  - type: web
    name: libraria-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    preDeployCommand: php artisan config:clear && php artisan route:clear && php artisan view:clear && php artisan migrate --force && php artisan db:seed --force
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: FORCE_HTTPS
        value: "true"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: DB_URL
        sync: false
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: MAIL_MAILER
        value: resend
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: onboarding@resend.dev
      - key: MAIL_FROM_NAME
        value: Libraria

  - type: worker
    name: libraria-queue
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    dockerCommand: php artisan queue:work database --queue=default --tries=3 --timeout=90 --sleep=3
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: FORCE_HTTPS
        value: "true"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: DB_URL
        sync: false
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: MAIL_MAILER
        value: resend
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: Libraria