[program:libraria-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/libraria/artisan queue:work database --queue=default --tries=3 --timeout=90 --sleep=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/libraria-queue.log
stopwaitsecs=3600
